language: python
python:
  - "3.6"
env:
  - DEVBOX=travis
addons:
  mariadb: '10.0'
before_install:
  - mysql -e "CREATE DATABASE blog;"
  - mysql blog < migrations/latest.sql
install:
  - pip install -r requirements.txt
script: python tests/run.py
