language: python
python:
  - "3.6"
  - "3.7"
services:
  - mysql
before_install:
  - mysql -u root --password="" < migrations/latest.sql
install:
  - pip install -r requirements.txt
script: python tests/run.py
