language: python
python:
- '3.6'
env:
- DEVBOX=travis
addons:
  mariadb: '10.0'
before_install:
- mysql -e "CREATE DATABASE blog;"
- mysql blog < migrations/latest.sql
install:
- pip install -r requirements.txt
script: python tests/run.py
before_deploy:
- openssl aes-256-cbc -K $encrypted_0df20a251864_key -iv $encrypted_0df20a251864_iv -in deploy/deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: "./deploy/deploy.sh"
  on:
    branch: master
