#!/usr/bin/env python3.6

# Modules for CGI and Templating
from __future__ import print_function
import lib.app as app
import os

def getArticles():
	cur = conn.cursor(app.MySQLdb.cursors.DictCursor)
	cur.execute("SELECT * FROM articles ORDER BY created DESC")
	articles = cur.fetchall()

	return articles


def main():
	stash['articles'] = getArticles()

	utils.render()

if __name__ == '__main__':
	stash = {}
	utils = app.App(os.path.split(__file__), stash)
	conn = utils.setupDB()

	main()

