#!/usr/bin/env python3.6

# Modules for CGI and Templating
from __future__ import print_function
import lib.app as app
import os

def main():
	stash = {}
	utils = app.App(os.path.split(__file__), stash)
	conn = utils.setupDB()
	utils.render()

if __name__ == '__main__':
	main()

